services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    container_name: api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - ./api/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"