services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api: &base
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    container_name: api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - ./api/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    entrypoint: /app/entrypoint.sh
    command:
      - "uvicorn"
      - "main:app"
      - "--reload"
      - "--host"
      - "0.0.0.0"
  migrations:
    <<: *base
    container_name: migrations
    ports: []
    command: 
      - "echo"
      - "do migrations"