"""Third migration

Revision ID: 2f37d5a95ee6
Revises: e5eb824de8ea
Create Date: 2023-12-13 04:33:41.137142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f37d5a95ee6'
down_revision: Union[str, None] = 'e5eb824de8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'owner_id')
    # ### end Alembic commands ###
