"""Add costs to product model

Revision ID: 3a8c230e9ead
Revises: ae54c9c77378
Create Date: 2023-12-14 05:06:22.106155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8c230e9ead'
down_revision: Union[str, None] = 'ae54c9c77378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('material_cost', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('product', sa.Column('production_cost', sa.ARRAY(sa.Integer()), nullable=True))
    op.create_foreign_key(None, 'product', 'material_cost', ['material_cost'], ['id'])
    op.create_foreign_key(None, 'product', 'production_cost', ['production_cost'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'production_cost')
    op.drop_column('product', 'material_cost')
    # ### end Alembic commands ###
