"""Tag list to product

Revision ID: ae54c9c77378
Revises: 2f37d5a95ee6
Create Date: 2023-12-14 05:02:20.453952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae54c9c77378'
down_revision: Union[str, None] = '2f37d5a95ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'tags')
    # ### end Alembic commands ###
